spring:
  profiles.active: dev
  application.name: OrderManagement
---
spring:
  profiles: dev
server:
  servlet:
    context-path: /dev
  port : 8888
  
---
spring:
  profiles: production

     
    