spring:
  profiles.active: dev
  application.name: OrderManagement
  datasource:
    url: jdbc:h2:mem:InventoryManagement
    driverClassName : org.h2.Driver
    username: sa
    password:
  jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2.console.enabled : true
    
jwt:
  secret: 144073
  expiryHours: 4
  token.uri: /authenticate
  username: 144073_Veera
  password: $2a$10$slYQmyNdGzTn7ZLBXBChFOC9f6kFjAqPhccnP6DxlWXx2lPk1C3G6
  
server:
  port : 8889
  
inventory:
  #url: http://localhost:7777/dev/checkproductavail/
  url: http://inventory:7777/dev/checkproductavail/ 
---
spring:
  profiles: dev
server:
  servlet:
    context-path: /dev
  port : 8888

inventory:
  #url: http://localhost:7777/dev/checkproductavail/
  url: http://inventory:7778/checkproductavail/   
---
spring:
  profiles: production

---
spring:
  profiles: test
inventory:
  url: http://localhost:7777/dev/checkproductavail/     
    