package com.sl.ms.ordermanagement;
//*************************************************

class  OrderItemData {
	String jsonString2	= "{\r\n"
			+ "    \"id\": 2,\r\n"
			+ "    \"name\": \"Veera2\",\r\n"
			+ "    \"total_amount\": 100.0,\r\n"
			+ "    \"items\": [\r\n"
			+ "        {\r\n"
			+ "            \"id\": 1,\r\n"
			+ "            \"name\": \"Item1\",\r\n"
			+ "            \"quantity\": \"1\",\r\n"
			+ "            \"price\": \"10\",\r\n"
			+ "            \"amount\": \"100\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"id\": 2,\r\n"
			+ "            \"name\": \"Item2\",\r\n"
			+ "            \"quantity\": \"1\",\r\n"
			+ "            \"price\": \"10\",\r\n"
			+ "            \"amount\": \"100\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"id\": 3,\r\n"
			+ "            \"name\": \"Item3\",\r\n"
			+ "            \"quantity\": \"1\",\r\n"
			+ "            \"price\": \"10\",\r\n"
			+ "            \"amount\": \"100\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"id\": 4,\r\n"
			+ "            \"name\": \"Item4\",\r\n"
			+ "            \"quantity\": \"1\",\r\n"
			+ "            \"price\": \"10\",\r\n"
			+ "            \"amount\": \"100\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"id\": 5,\r\n"
			+ "            \"name\": \"Item5\",\r\n"
			+ "            \"quantity\": \"1\",\r\n"
			+ "            \"price\": \"10\",\r\n"
			+ "            \"amount\": \"100\"\r\n"
			+ "        }\r\n"
			+ "    ]\r\n"
			+ "}";
	String jsonString1	= "{\r\n"
			+ "    \"id\": 1,\r\n"
			+ "    \"name\": \"Veera1\",\r\n"
			+ "    \"total_amount\": 100.0,\r\n"
			+ "    \"items\": [\r\n"
			+ "        {\r\n"
			+ "            \"id\": 1,\r\n"
			+ "            \"name\": \"Item11\",\r\n"
			+ "            \"quantity\": \"1\",\r\n"
			+ "            \"price\": \"10\",\r\n"
			+ "            \"amount\": \"100\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"id\": 2,\r\n"
			+ "            \"name\": \"Item12\",\r\n"
			+ "            \"quantity\": \"1\",\r\n"
			+ "            \"price\": \"10\",\r\n"
			+ "            \"amount\": \"100\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"id\": 3,\r\n"
			+ "            \"name\": \"Item13\",\r\n"
			+ "            \"quantity\": \"1\",\r\n"
			+ "            \"price\": \"10\",\r\n"
			+ "            \"amount\": \"100\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"id\": 4,\r\n"
			+ "            \"name\": \"Item14\",\r\n"
			+ "            \"quantity\": \"1\",\r\n"
			+ "            \"price\": \"10\",\r\n"
			+ "            \"amount\": \"100\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"id\": 5,\r\n"
			+ "            \"name\": \"Item15\",\r\n"
			+ "            \"quantity\": \"1\",\r\n"
			+ "            \"price\": \"10\",\r\n"
			+ "            \"amount\": \"100\"\r\n"
			+ "        }\r\n"
			+ "    ]\r\n"
			+ "}";
}

